baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Oi's Kitchen"
googleAnalytics = "UA-1234567-12"

[params]
    author = "Oi Cheepchaiissara"
    description = "Easily cook incredible Thai cuisine with simple and refined step-by-step recipes."
    subtitle = "Easily cook incredible Thai cuisine with simple and refined step-by-step recipes."
    themecolour = "#ffffff"
    twitter = "@oiskitchen"

[author]    
name = "Oi Cheepchaiissara"

# The top navigation menu links. Home included first by default:
[[menu.main]]
    name = "Thai Recipes"
    identifier = "recipes"
    url = "/thai-recipes/"
    weight = 2
[[menu.main]]
    name = "Colchester Cooking Classes"
    identifier = "classes"
    url = "/colchester-cooking-classes/"
    weight = 3
[[menu.main]]
    name = "Shop"
    identifier = "shop"
    url = "/shop/"
    weight = 4
[[menu.main]]
    name = "About Oi"
    identifier = "about"
    url = "/about-oi/"
    weight = 5
[[menu.main]]
    name = "Contact"
    identifier = "contact"
    url = "/contact/"
    weight = 6